//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mobile_Shop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Purchase_Master
    {
        public int ID { get; set; }
        public int PO_NO { get; set; }
        public Nullable<System.DateTime> PO_Date { get; set; }
        public int SupplierID { get; set; }
        public string Remarks { get; set; }
    
        public virtual Supplier Supplier { get; set; }
    }
}
