//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mobile_Shop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sales_Master
    {
        
    
        public int ID { get; set; }
        public int Customer_ID { get; set; }
        public Nullable<System.DateTime> Sales_Date { get; set; }
        public string PAN { get; set; }
        public string Remarks { get; set; }
    
        public virtual Customer Customer { get; set; }
        
    }
}
