//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mobile_Shop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sales_Details
    {
        public int ID { get; set; }
        public int Sales_ID { get; set; }
        public int Product_ID { get; set; }
        public int Quantity { get; set; }
        public string UOM { get; set; }
        public int Rate { get; set; }
        public int Amount { get; set; }
        public Nullable<int> Discount { get; set; }
        public decimal Tax { get; set; }
        public int Tax_Amount { get; set; }
        public int Net_Amount { get; set; }
    
        public virtual Product Product { get; set; }
    }
}
